services:
  dash_provider:
    build: .
    env_file:
      - path: .env
      - path: .env.prod
    ports:
      - "${SERVICES_PORT:-8002}:${SERVICES_PORT:-8002}"
    extra_hosts:
      - "host.docker.internal:host-gateway"

    develop:
      watch:
        - action: sync+restart
          path: .
          target: /app
        - action: rebuild
          path: pyproject.toml

