services:
  dash_provider:
    build: .
    env_file:
      - path: ./.env
      - path: ./.env.prod
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"

    develop:
      watch:
        - action: sync+restart
          path: .
          target: /app
        - action: rebuild
          path: pyproject.toml

